SELECT* FROM Bank_Loan_data
-- TOTAL APPLICATION KPI QUERIES
SELECT COUNT(id)  AS Total_Loan_Applications FROM  Bank_Loan_data


SELECT COUNT(id)  AS  MTD_Total_Loan_Applications FROM  Bank_Loan_data
WHERE MONTH(issue_date)= 12 AND YEAR(issue_date)= 2021

SELECT COUNT(id)  AS  PMTD_Total_Loan_Applications FROM  Bank_Loan_data
WHERE MONTH(issue_date)= 11 AND YEAR(issue_date)= 2021


-- TOTAL AMOUNT FUNDED KPI QUERIES
SELECT SUM(loan_amount) AS TOTAL_FUNDED_LOAN_AMOUNT FROM Bank_Loan_data

-- TOTAL FUNDED AMOUNT MTD
SELECT SUM(loan_amount) AS MTD_TOTAL_FUNDED_LOAN_AMOUNT FROM Bank_Loan_data
WHERE MONTH(issue_date) = 12  AND YEAR(issue_date) = 2021

-- TOTAL FUNDED AMOUNT PMTD
SELECT SUM(loan_amount) AS PMTD_TOTAL_FUNDED_LOAN_AMOUNT FROM Bank_Loan_data
WHERE MONTH(issue_date) = 11 AND YEAR(issue_date)= 2021

-- TOTAL AMOUNT RECEIVED AS REPAYMENT OF LOAN
SELECT SUM (total_payment) AS TOTAL_AMOUNT_RECEIVED FROM Bank_Loan_data

--TOTAL AMOUNT RECEIVED MTD
SELECT SUM (total_payment) AS MTD_TOTAL_AMOUNT_RECEIVED FROM Bank_Loan_data
WHERE MONTH (issue_date)= 12 AND YEAR(issue_date)= 2021

-- TOTAL AMOUNT RECEIVED PMTD
SELECT SUM (total_payment) AS MTD_TOTAL_AMOUNT_RECEIVED FROM Bank_Loan_data
WHERE MONTH (issue_date)= 11 AND YEAR(issue_date)= 2021

-- AVERAGE INTEREST RATE
SELECT AVG(int_rate)*100 AS AVG_INTEREST_RATE FROM Bank_Loan_data

-- MTD AVERAGE INTEREST RATE
SELECT ROUND(AVG(int_rate)*100,4) AS MTD_AVG_INTEREST_RATE FROM Bank_Loan_data
WHERE MONTH(issue_date)= 12 AND YEAR(issue_date)=2021 

-- PMTD AVERAGE INTEREST RATE
SELECT ROUND(AVG(int_rate)*100,4) AS PMTD_AVG_INTEREST_RATE FROM Bank_Loan_data
WHERE MONTH(issue_date)= 11 AND YEAR(issue_date)=2021 

--AVERAGE DTI
SELECT ROUND(AVG(dti),4)*100 AS AVG_DTI FROM  Bank_Loan_data

-- MTD AVERAGE DTI
SELECT ROUND(AVG(dti),4)*100 AS MTD_AVG_DTI FROM  Bank_Loan_data
WHERE MONTH(issue_date)=12 AND YEAR(issue_date)= 2021

-- PMTD AVERAGE DTI 
SELECT ROUND(AVG(dti),4)*100 AS MTD_AVG_DTI FROM  Bank_Loan_data
WHERE MONTH(issue_date)=11 AND YEAR(issue_date)= 2021

-- LOAN DATA GRID VIEW
 SELECT 
	LOAN_STATUS,
	COUNT(ID) AS TOTAL_APPLICATIONS,
	SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED,
	SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT,
	AVG(INT_RATE*100) AS AVERAGE_INTEREST_RATE,
	AVG(DTI*100) AS AVERAGE_DEBT_TO_INCOME
FROM
	BANK_LOAN_DATA
GROUP BY 
	LOAN_STATUS



-- MONTH-TO-DATE
SELECT
	LOAN_STATUS,
	SUM(TOTAL_PAYMENT) AS MTD_AMOUNT_RECEIVED,
	SUM (LOAN_AMOUNT) AS MTD_AMOUNT_FUNDED
FROM Bank_Loan_data
WHERE MONTH(ISSUE_DATE) = 12
GROUP BY LOAN_STATUS

