-- OVERVIEW BANK REPORT.
SELECT * FROM Bank_Loan_data
-- MONTHLY TREND ANALYSIS
SELECT 
	MONTH(ISSUE_DATE) AS SERIAL_NO,
	DATENAME (MONTH, issue_date) AS MONTH_NAME,
	COUNT(id) AS TOTAL_LOAN_APPLICATION,
	SUM(loan_amount) AS TOTAL_FUNDED_AMOUNT,
	SUM(total_payment) AS TOTAL_AMOUNT_RECEIVED
FROM Bank_Loan_data
GROUP BY MONTH(ISSUE_DATE),DATENAME(MONTH, issue_date)
ORDER BY MONTH(issue_date) 

-- REGIONAL ANALYSIS BY STATE

SELECT
	address_state AS STATE,
	COUNT(ID) AS TOTAL_LOAN_APPLICATION,
	SUM(loan_amount) AS TOTAL_FUNDED_AMOUNT,
	SUM(total_payment) AS TOTAL_AMOUNT_RECEIVED
FROM Bank_Loan_data
GROUP BY address_state
ORDER BY SUM(loan_amount) DESC

-- LOAN TERM ANALYSIS
SELECT
	term AS LOAN_TERM,
	COUNT(ID) AS TOTAL_LOAN_APPLICATION,
	SUM(loan_amount) AS TOTAL_FUNDED_AMOUNT,
	SUM(total_payment) AS TOTAL_AMOUNT_RECEIVED
FROM Bank_Loan_data
GROUP BY term
ORDER BY term

--EMPLOYEE LENGTH ANALYSIS
SELECT
	emp_length AS EMPLOYEE_LENGTH,
	COUNT(ID) AS TOTAL_LOAN_APPLICATION,
	SUM(loan_amount) AS TOTAL_FUNDED_AMOUNT,
	SUM(total_payment) AS TOTAL_AMOUNT_RECEIVED
FROM Bank_Loan_data
GROUP BY emp_length
ORDER BY emp_length 

-- PURPOSE ANALYSIS
SELECT
	purpose AS PURPOSE,
	COUNT(ID) AS TOTAL_LOAN_APPLICATION,
	SUM(loan_amount) AS TOTAL_FUNDED_AMOUNT,
	SUM(total_payment) AS TOTAL_AMOUNT_RECEIVED
FROM Bank_Loan_data
GROUP BY purpose
ORDER BY purpose

-- HOME OWNERSHIP ANALYSIS
SELECT
	home_ownership AS OWNERSHIP_STATUS,
	COUNT(ID) AS TOTAL_LOAN_APPLICATION,
	SUM(loan_amount) AS TOTAL_FUNDED_AMOUNT,
	SUM(total_payment) AS TOTAL_AMOUNT_RECEIVED
FROM Bank_Loan_data
GROUP BY home_ownership
ORDER BY home_ownership

-- GRADE ANALYSIS
SELECT
	GRADE AS GRADE_RATING,
	COUNT(ID) AS TOTAL_LOAN_APPLICATION,
	SUM(loan_amount) AS TOTAL_FUNDED_AMOUNT,
	SUM(total_payment) AS TOTAL_AMOUNT_RECEIVED
FROM Bank_Loan_data
GROUP BY grade
ORDER BY grade